apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stack
spec:
  releaseName: monitoring-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: "20.0.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false

        ruleSelectorNilUsesHelmValues: false
        # ruleSelector:
        #   matchLabels:
        #     app: strimzi

        podMonitorSelectorNilUsesHelmValues: false
        # podMonitorSelector:
        #   matchLabels:
        #     app: strimzi
