apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tracking.identity.login-attempt
  namespace: kafka
  labels:
    strimzi.io/cluster: dev
spec:
  partitions: 1
  replicas: 1
  config:
    segment.ms: 3600000 # 1 hour
    segment.bytes: 512000000 # 512mb
    retention.ms: 21600000 # 6 hours
